// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gorlqqzogbmrpjubfwco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcmxxcXpvZ2JtcnBqdWJmd2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjcyMzksImV4cCI6MjA2MzM0MzIzOX0.lK3LzndL6DLpEIncj4yoXbcmPLMWGv8rom_U9b9kNv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);